"""Commands to scaffold SKILL.md files for AI assistants."""


import os
import shutil
from pathlib import Path
from typing import Annotated, Optional

import typer

from hf_cloud import __version__

DEFAULT_SKILL_ID = "hf-cloud"
LOCAL_CENTRAL_SKILLS_DIR = Path(".agents/skills")
GLOBAL_CENTRAL_SKILLS_DIR = Path("~/.agents/skills")

LOCAL_AGENT_SKILLS_DIRS = {
    "codex": Path(".codex/skills"),
    "claude": Path(".claude/skills"),
    "cursor": Path(".cursor/skills"),
    "opencode": Path(".config/opencode/skills"),
}

GLOBAL_AGENT_SKILLS_DIRS = {
    "codex": Path("~/.codex/skills"),
    "claude": Path("~/.claude/skills"),
    "cursor": Path("~/.cursor/skills"),
    "opencode": Path("~/.config/opencode/skills"),
}

skills_app = typer.Typer(help="Manage AI assistant skills for hf-cloud.")


def build_skill_md() -> str:
    """Build default SKILL.md content for hf-cloud."""
    return f"""---
name: hf-cloud
description: Deploy and manage Hugging Face model endpoints across cloud providers.
---

Generated by `hf-cloud skills add` (v{__version__}).

Preferred invocation:
- `hf cloud ...` (Hugging Face CLI extension install)

Standalone fallback:
- `hf-cloud ...`

## Recommended workflow
1. Configure provider defaults:
   - `hf cloud providers configure sagemaker`
   - `hf cloud providers configure vertex`
2. Estimate minimum viable instances before deployment:
   - `hf cloud sagemaker estimate MODEL_ID`
   - `hf cloud vertex estimate MODEL_ID`
3. Deploy a model:
   - `hf cloud sagemaker deploy MODEL_ID --name NAME`
   - `hf cloud vertex deploy MODEL_ID --name NAME`
4. Verify and test:
   - `hf cloud sagemaker status DEPLOYMENT_ID`
   - `hf cloud vertex status DEPLOYMENT_ID`
   - `hf cloud sagemaker invoke DEPLOYMENT_ID --input "Hello"`
5. Clean up:
   - `hf cloud sagemaker delete DEPLOYMENT_ID`
   - `hf cloud vertex delete DEPLOYMENT_ID`

## Useful commands
- `hf cloud ls`
- `hf cloud providers ls`
- `hf cloud sagemaker ls`
- `hf cloud vertex ls`

Tip: if you use standalone installation, replace `hf cloud` with `hf-cloud`.
"""


def _remove_existing(path: Path, force: bool) -> None:
    """Delete an existing file/dir/symlink if --force is set."""
    if not (path.exists() or path.is_symlink()):
        return
    if not force:
        typer.echo(f"Skill already exists at {path}. Re-run with --force to overwrite.")
        raise typer.Exit(
            code=1,
        )
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink()


def _install_skill(skills_dir: Path, force: bool) -> Path:
    """Install SKILL.md under a target skills directory."""
    resolved_dir = skills_dir.expanduser().resolve()
    resolved_dir.mkdir(parents=True, exist_ok=True)
    dest = resolved_dir / DEFAULT_SKILL_ID

    _remove_existing(dest, force)
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "SKILL.md").write_text(build_skill_md(), encoding="utf-8")
    return dest


def _symlink_skill(agent_skills_dir: Path, central_skill_path: Path, force: bool) -> Path:
    """Create a relative symlink to a central skill path for one assistant."""
    resolved_agent_dir = agent_skills_dir.expanduser().resolve()
    resolved_agent_dir.mkdir(parents=True, exist_ok=True)
    link_path = resolved_agent_dir / DEFAULT_SKILL_ID

    _remove_existing(link_path, force)
    link_path.symlink_to(os.path.relpath(central_skill_path, resolved_agent_dir))
    return link_path


@skills_app.command(name="preview")
def preview_skill() -> None:
    """Print the SKILL.md template to stdout."""
    typer.echo(build_skill_md())


@skills_app.command(name="add")
def add_skill(
    codex: Annotated[bool, typer.Option("--codex", help="Symlink skill into Codex skills directory.")] = False,
    claude: Annotated[bool, typer.Option("--claude", help="Symlink skill into Claude skills directory.")] = False,
    cursor: Annotated[bool, typer.Option("--cursor", help="Symlink skill into Cursor skills directory.")] = False,
    opencode: Annotated[
        bool, typer.Option("--opencode", help="Symlink skill into OpenCode skills directory.")
    ] = False,
    global_: Annotated[
        bool,
        typer.Option("--global", "-g", help="Install in user-level directory instead of current project."),
    ] = False,
    dest: Annotated[
        Optional[Path],
        typer.Option(help="Custom destination directory (path to a skills directory)."),
    ] = None,
    force: Annotated[bool, typer.Option("--force", help="Overwrite existing skill files if present.")] = False,
) -> None:
    """Create an hf-cloud SKILL.md and optionally symlink it into assistant directories."""
    if dest and (codex or claude or cursor or opencode or global_):
        typer.echo("--dest cannot be combined with assistant flags or --global.")
        raise typer.Exit(code=1)

    if dest:
        skill_path = _install_skill(dest, force)
        typer.echo(f"Installed skill at: {skill_path}")
        return

    central_dir = GLOBAL_CENTRAL_SKILLS_DIR if global_ else LOCAL_CENTRAL_SKILLS_DIR
    central_skill_path = _install_skill(central_dir, force)
    typer.echo(f"Installed central skill at: {central_skill_path}")

    targets = GLOBAL_AGENT_SKILLS_DIRS if global_ else LOCAL_AGENT_SKILLS_DIRS
    selected = []
    if codex:
        selected.append(targets["codex"])
    if claude:
        selected.append(targets["claude"])
    if cursor:
        selected.append(targets["cursor"])
    if opencode:
        selected.append(targets["opencode"])

    for target in selected:
        link = _symlink_skill(target, central_skill_path, force)
        typer.echo(f"Linked skill at: {link}")
